# Generated by Django 6.0.8 on 2026-08-14 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_fileupload_cid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='accessble_users',
            field=models.ManyToManyField(blank=True, related_name='accessble_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
